// Portions generated by GENAI: Claude Sonnet 4.5
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  site: 'https://swetankambar.github.io',
  base: '/',
  outDir: 'dist',
});

