// Portions generated by GENAI: Claude Sonnet 4.5
import Fuse from 'fuse.js';

interface SearchPost {
	slug: string;
	title: string;
	description: string;
	tags: string[];
}

let fuse: Fuse<SearchPost> | null = null;
let selectedIndex = 0;

// Initialize Fuse.js
function initSearch() {
	const posts = (window as any).searchPosts || [];
	
	fuse = new Fuse(posts, {
		keys: [
			{ name: 'title', weight: 2 },
			{ name: 'description', weight: 1 },
			{ name: 'tags', weight: 1.5 },
		],
		threshold: 0.3,
		includeScore: true,
		minMatchCharLength: 2,
	});
}

// Open search modal
export function openSearch() {
	const modal = document.getElementById('search-modal');
	const input = document.getElementById('search-input') as HTMLInputElement;
	
	if (modal && input) {
		modal.setAttribute('aria-hidden', 'false');
		document.body.style.overflow = 'hidden';
		input.focus();
		
		if (!fuse) {
			initSearch();
		}
	}
}

// Close search modal
export function closeSearch() {
	const modal = document.getElementById('search-modal');
	const input = document.getElementById('search-input') as HTMLInputElement;
	const results = document.getElementById('search-results');
	
	if (modal && input && results) {
		modal.setAttribute('aria-hidden', 'true');
		document.body.style.overflow = '';
		input.value = '';
		results.innerHTML = '';
		selectedIndex = 0;
	}
}

// Perform search
function performSearch(query: string) {
	const results = document.getElementById('search-results');
	if (!results || !fuse) return;
	
	if (query.length < 2) {
		results.innerHTML = '';
		return;
	}
	
	const searchResults = fuse.search(query);
	selectedIndex = 0;
	
	if (searchResults.length === 0) {
		results.innerHTML = '<div class="search-no-results">No results found</div>';
		return;
	}
	
	results.innerHTML = searchResults
		.slice(0, 10)
		.map((result, index) => {
			const post = result.item;
			return `
				<div class="search-result-item ${index === 0 ? 'selected' : ''}" data-index="${index}" data-slug="${post.slug}">
					<div class="search-result-title">${post.title}</div>
					<div class="search-result-description">${post.description}</div>
					${post.tags.length > 0 ? `
						<div class="search-result-tags">
							${post.tags.slice(0, 3).map(tag => `<span class="tag">${tag}</span>`).join('')}
						</div>
					` : ''}
				</div>
			`;
		})
		.join('');
	
	// Add click handlers
	results.querySelectorAll('.search-result-item').forEach((item) => {
		item.addEventListener('click', () => {
			const slug = item.getAttribute('data-slug');
			if (slug) {
				window.location.href = `/blog/${slug}/`;
			}
		});
	});
}

// Navigate results with keyboard
function navigateResults(direction: 'up' | 'down') {
	const results = document.getElementById('search-results');
	if (!results) return;
	
	const items = results.querySelectorAll('.search-result-item');
	if (items.length === 0) return;
	
	items[selectedIndex]?.classList.remove('selected');
	
	if (direction === 'down') {
		selectedIndex = (selectedIndex + 1) % items.length;
	} else {
		selectedIndex = (selectedIndex - 1 + items.length) % items.length;
	}
	
	items[selectedIndex]?.classList.add('selected');
	items[selectedIndex]?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
}

// Select current result
function selectResult() {
	const results = document.getElementById('search-results');
	if (!results) return;
	
	const items = results.querySelectorAll('.search-result-item');
	const selectedItem = items[selectedIndex];
	
	if (selectedItem) {
		const slug = selectedItem.getAttribute('data-slug');
		if (slug) {
			window.location.href = `/blog/${slug}/`;
		}
	}
}

// Initialize event listeners
export function initSearchListeners() {
	const searchButton = document.getElementById('search-button');
	const searchClose = document.getElementById('search-close');
	const searchInput = document.getElementById('search-input') as HTMLInputElement;
	const modal = document.getElementById('search-modal');
	
	// Open search
	searchButton?.addEventListener('click', openSearch);
	
	// Close search
	searchClose?.addEventListener('click', closeSearch);
	modal?.addEventListener('click', (e) => {
		if (e.target === modal) {
			closeSearch();
		}
	});
	
	// Search input
	searchInput?.addEventListener('input', (e) => {
		const query = (e.target as HTMLInputElement).value;
		performSearch(query);
	});
	
	// Keyboard shortcuts
	document.addEventListener('keydown', (e) => {
		// Cmd/Ctrl + K to open search
		if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
			e.preventDefault();
			openSearch();
			return;
		}
		
		// Only handle these keys when modal is open
		const isModalOpen = modal?.getAttribute('aria-hidden') === 'false';
		if (!isModalOpen) return;
		
		switch (e.key) {
			case 'Escape':
				e.preventDefault();
				closeSearch();
				break;
			case 'ArrowDown':
				e.preventDefault();
				navigateResults('down');
				break;
			case 'ArrowUp':
				e.preventDefault();
				navigateResults('up');
				break;
			case 'Enter':
				e.preventDefault();
				selectResult();
				break;
		}
	});
}

// Auto-initialize when DOM is ready
if (typeof window !== 'undefined') {
	if (document.readyState === 'loading') {
		document.addEventListener('DOMContentLoaded', initSearchListeners);
	} else {
		initSearchListeners();
	}
}

