// Portions generated by GENAI: Claude Sonnet 4.5
import rss from '@astrojs/rss';
import { getCollection } from 'astro:content';

export async function GET(context) {
	const posts = await getCollection('blog');
	return rss({
		title: 'Samvet',
		description: 'Ensemble of my thoughts, experiments and observations',
		site: context.site,
		items: posts.map((post) => ({
			...post.data,
			link: `/blog/${post.slug}/`,
		})),
	});
}

